### ISSUE TITLE
Account Creation and Login

### ISSUE THREAD

**Issue by EaTea** [EaTea/CITS4230-Project-Group-7#11]
Allow an unregistered user to create an account and a registered user to log into the system and view their tasks and to-do lists.

**Comment by N-Yuki** [comment]
I've got this covered, and it is working in the user-login branch.
I'll be adding in other permission/restriction stuff later to make it so users don't get access to all the views. I've already done the restrictions for the User controller, though, since it prevented the signup page from loading properly.

**Comment by N-Yuki** [comment]
This should be in master now.
