### ISSUE TITLE
To-Do System Development (Stage 2)

### ISSUE THREAD

**Issue by sontobgay** [EaTea/CITS4230-Project-Group-7#27]
@EaTea, @S0uten:
All are aware that lots of stuffs are going on our github repo interms of discussing issues, updating wikis, configuration of rails and application directory structures and github handlings. However, whats on light interms of the actual system development using rails. Besides the DB, who is doing what in rails and which module or functionality has come up? I am saying strictly from the point of actual coding in rails. I accept, I am failing on some parts [Partly because I am engaged in some of my other unit assignments as well], but what thing has come up prominently? considering the limited time (Aprox: 3 weeks for the assignment) for the assignment. 

Please guide me. May be I am misunderstanding something. I am lost in the midst of GITHUB stuffs and I don't see any progress on development of actual system functionalities not only from my side, but from other members as well!

**Comment by N-Yuki** [comment]
Yeah, we are limited on time, so we do want to get more of the system part done.
From my understanding, EaTea is currently not working on this as he said he was working on some other assignment, but we should see some activity again soon.
Also, I have an assessment in the coming week, so I'll probably be inactive for a few days from this.

Anyway, to answer the question, I've been looking into the login system stuff, so I can take that if no one else has worked on it yet.
Although, as you may have noticed from the Git history, I've been working on fixing, maintaining, reconfiguring and integrating a bunch of things in the repo, so I have been busy working on them.

I'm not quite sure what is happening with the list and task creation, though.

(I added the @'s in the main post to show who it is mentioning)

**Comment by EaTea** [comment]
I can do some of this, I think, but I was hoping to get the migration done first. This was why I was asking about the migration earlier --- that'd probably streamline the process a lot more, so that we wouldn't need to have worried so much about some of the lower-level interaction. The problems with setting up the database appear to be a little worrying, though, so I'll try looking into it and seeing how the database interaction code should look like.

In terms of when I'll be available, tomorrow night some time will probably be when I'll be working on parts of the functionality, and I understand that you're all busy as well with some of your own assessments.

I didn't think it'd be as productive to start saying who should be doing what without everyone actually being able to meet and discuss this, but sontobgay makes a good point that we need to really figure this out soon. Can we meet on Monday at 1pm? Otherwise this is going to be another end-of-semester-we're-rushing-our-heads-off project (or that's my intuition, anyway...sorry...)

**Comment by sontobgay** [comment]
I ll be available for our usual meeting time. That's at 1 pm Monday.

**Comment by N-Yuki** [comment]
@sontobgay, @EaTea:
Make sure to check out the new master. There's been a lot merged in now.
Also, remember to make a pull request when something is ready for master.
And, remember to close any issues that have been solved.

**Comment by N-Yuki** [comment]
Also, I've uploaded the latest master to the group server, and I'll do so periodically as things come in.
