### ISSUE TITLE
Improve the looks of the general pages

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#28]
Once we have the actual to-do system working, we should replace the slideshow images with screenshots of the system where appropriate.
Also, the features page could also do with screenshots.
The other pages could also do with some eye candy (could help with demonstrating more CSS and ECMAScript usage) as well since they are a little dull with just being a wall of text.

**Comment by EaTea** [comment]
I'll need to rewrite some of the walls-of-text I think. And yes, improving the look-and-feel would be good once we're done. Maybe a HTML5 screenshot gallery maybe on the "Features" side using transitions in CSS would be a nifty little feature to add in, as a suggestion.

Also, I'd like to make this a discussion so that everyone can just pitch some ideas as to what might be a cool thing we could do to improve the look of our pages.
