### ISSUE TITLE
Redirection isn't working properly

### ISSUE THREAD

**Issue by EaTea** [EaTea/CITS4230-Project-Group-7#41]
See 5af16efe1ee657c79b9ecba794e1af48d08b400e . The problem is that I can't get redirects working properly inside the controllers, resulting in the iframe wandering off to a place it shouldn't go to or, as the code does in the above commit errorring altogether.

This is a pretty big issue, and if we can fix it our interface goes a long way toward looking much more presentable.

**Comment by N-Yuki** [comment]
That's not a very good defect description. If I can't reproduce the bug nor work out the expected behaviour without trying to understand the logic of some code, I'm wasting my time.

Also, rather than a defect report, from my understanding, it just seems like you are asking if we know what's wrong with the syntax of some code. If this is true, I'll change the title to sound more like a question and change the label to misc.

Anyway, I suggested what you might be looking for on the commit mentioned.

**Comment by EaTea** [comment]
6am was never a good time to make a defect report.

No, this is not just a syntax problem. There should be the same problem within the commit before this one. This is not a simple syntax problem, and if you can't reproduce it then something must have somehow fixed itself. If that's the case then I'm extremely confused. Perhaps I have introduced an error somewhere else...=S

**Comment by N-Yuki** [comment]
Sorry, I meant that I couldn't reproduce the bug with the information given. After reading the code, I think I might understand how to trigger this "bug" - considering that I don't fully understand the bug, I can't be sure if I'll be reproducing the bug you are mentioning, though.
