### ISSUE TITLE
Change permissions for Editing User Details

### ISSUE THREAD

**Issue by EaTea** [EaTea/CITS4230-Project-Group-7#44]
Users will want to edit their own details but right now the permissions are set up so that Admin is the only one who can edit details. Could this possibly be changed? Or is there some inherent security flaw that I'm missing?

**Comment by N-Yuki** [comment]
Okay, I allowed access to the show and update actions with the restriction that users can only access their own details.

I can also add access to the edit action, but the current view should be improved first. Otherwise, just have some other UI component, say in the dash, which does what's needed by calling the update action.

**Comment by N-Yuki** [comment]
Done.
